### ISSUE TITLE
Push module Firebase error.

### ISSUE THREAD

**Issue by developer2311** [chat-sdk/chat-sdk-ios#321]
1. **Is the bug present in the demo Chat SDK project?**
-
2. **What modifications have you made to the Chat SDK?**
I did update version of SDK.
3. **iOS Version? Device or simulator?**
12.
4. **Steps taken to reproduce the problem:**
Send text message from one to another device.
5. **Expected result:**
Push notification sent and received.
6. **Actual result:**
Push notification didn't send and receive.
7. **Comments:**

I think that we have a problem with Push Notifications after your implementation Push Notifications via Firebase Cloud Functions. Probably, your index.js file contains some issues. 

Firebase logs contains: 

Error: data must only contain string values
    at FirebaseMessagingError.Error (native)
    at FirebaseMessagingError.FirebaseError [as constructor] (/user_code/node_modules/firebase-admin/lib/utils/error.js:39:28)
    at FirebaseMessagingError.PrefixedFirebaseError [as constructor] (/user_code/node_modules/firebase-admin/lib/utils/error.js:85:28)
    at new FirebaseMessagingError (/user_code/node_modules/firebase-admin/lib/utils/error.js:241:16)
    at /user_code/node_modules/firebase-admin/lib/messaging/messaging.js:95:19
    at Array.forEach (native)
    at validateStringMap (/user_code/node_modules/firebase-admin/lib/messaging/messaging.js:93:22)
    at validateMessage (/user_code/node_modules/firebase-admin/lib/messaging/messaging.js:358:5)
    at Messaging.send (/user_code/node_modules/firebase-admin/lib/messaging/messaging.js:497:9)
    at getUserIds.then (/user_code/index.js:224:39)

### **Could you help me to resolve it, please?**

**Comment by developer2311** [comment]
@bensmiley push notifications in my project are not working. Could you help me?

**Comment by NagaSyam** [comment]
@bensmiley I am also not receiving push notifications, please help.
Thanks

**Comment by failynsedik** [comment]
Hi. Are there any updates to this? 🙏🏼

**Comment by developer2311** [comment]
> Hi. Are there any updates to this? 🙏🏼

@failynsedik Hello. Last time I’ve resolved a problem with push notifications, I had to change Cloud Function code in Firebase. So I think, you should search for right solution on Firebase Cloud Function. Revise your cloud function's code and try again. But it was about 10 months ago. I don’t know for sure what changes could be implemented after that.

**Comment by failynsedik** [comment]
@developer2311 Setting up Firebase Cloud Function worked for us. Thanks a lot for this! 😁🎉

**Comment by developer2311** [comment]
> @developer2311 Setting up Firebase Cloud Function worked for us. Thanks a lot for this! 😁🎉

Welcome :)
